/**
 * Firestore Vehicle Schema
 * 
 * This file documents the structure of vehicle documents in Firestore.
 * Generated by seed-firestore.js according to application requirements.
 */

export type Drivetrain = 'awd' | '4wd' | 'fwd' | 'rwd';
export type Powertrain = 'hybrid' | 'ev' | 'gas' | 'phev';
export type BodyStyle = 'suv' | 'sedan' | 'truck' | 'crossover' | 'coupe' | 'hatchback' | 'minivan' | 'wagon';

/**
 * Main Vehicle document structure
 * Collection: vehicles
 * Document ID: {make}_{model}_{year}_{trim} (lowercase, underscores)
 */
export interface VehicleDocument {
  // Core identifiers
  id: string;                          // Document ID (same as Firestore doc key)
  name: string;                        // Display name: "2024 Toyota Camry XLE"
  img: string;                         // Image path: "/CarImages/camry.jpg"
  make: string;                        // "Toyota", "Lexus"
  model: string;                       // "Camry", "RAV4", "Highlander"
  year: number;                        // 2024, 2025
  trim: string;                        // "xle", "trd_off_road", "base"
  canonicalKey: string;                // "toyota|camry|2024|xle" (for deduplication)
  
  // Display fields (for UI components)
  description: string;                 // Brief description
  tags: string[];                      // Searchable tags: ["toyota", "suv", "hybrid", "awd", "family"]
  price: string;                       // Formatted price: "$28,855" or "Contact Dealer"
  
  // Specifications (matching Car type from src/lib/cars.ts)
  specs: {
    drivetrain: Drivetrain;            // "awd" | "4wd" | "fwd" | "rwd"
    powertrain: Powertrain;            // "hybrid" | "ev" | "gas" | "phev"
    body: BodyStyle;                   // "suv" | "sedan" | "truck" | etc.
    mpg?: string;                      // "39 mpg" (for gas/hybrid)
    range?: string;                    // "252 mi" (for EVs)
  };
  
  // Pricing details (for finance engine)
  pricing: {
    msrp: number | null;               // Manufacturer's suggested retail price
    invoice: number | null;            // Dealer invoice price (~93% of MSRP)
    destinationCharge: number;         // Shipping/delivery fee (typically $1,095)
  };
  
  // Performance metrics
  performance: {
    mpgCity: number | null;            // City MPG
    mpgHighway: number | null;         // Highway MPG
    mpgCombined: number | null;        // Combined MPG (or MPGe for EVs)
    engineDisplacement: number | null; // Liters (e.g., 2.5)
    cylinders: number | null;          // 4, 6, 8, etc. (null for EVs)
    horsepower: number | null;         // Would come from CarQuery API
    torque: number | null;             // Would come from CarQuery API
  };
  
  // Dimensions and capacity
  dimensions: {
    seating: number;                   // Number of seats (5, 7, 8)
    cargo: number | null;              // Cargo volume in cubic feet
    length: number | null;             // Inches
    width: number | null;              // Inches
    height: number | null;             // Inches
    wheelbase: number | null;          // Inches
  };
  
  // Features and equipment
  features: {
    standard: string[];                // Standard features: ["adaptive-cruise", "lane-keep"]
    safety: string[];                  // Safety features: ["abs", "stability-control"]
    technology: string[];              // Tech features: ["apple-carplay", "wifi-hotspot"]
    comfort: string[];                 // Comfort features: ["heated-seats", "dual-climate"]
    exterior: string[];                // Exterior features: ["roof-rails", "tow-package"]
  };
  
  // Availability and inventory
  availability: {
    available: boolean;                // Currently available for sale
    inventory: number;                 // Number of units in stock (from dealer API)
    estimatedDelivery: string;         // "4-6 weeks", "In Stock", etc.
  };
  
  // Source data (EPA)
  epa: {
    epa_model_year_id: string | null;
    epa_option_desc: string | null;    // Original EPA trim/option description
    city_mpg: number | null;
    highway_mpg: number | null;
    combined_mpg: number | null;
    fuel_type: string | null;          // Original EPA fuel type
    fuel_type_primary: string | null;  // "Regular Gasoline", "Premium Gasoline", "Electricity"
    fuel_type_secondary: string | null;// For hybrids: "Electricity"
    engine_displacement: number | null;
    cylinders: number | null;
    transmission: string | null;       // "Automatic 8-spd", "CVT", etc.
    drive_type: string | null;         // Original EPA drive type description
    vehicle_class: string | null;      // "Midsize Car", "Small SUV", etc.
    vehicle_type: string | null;       // "Midsize Cars", "Small Sport Utility Vehicle 4WD"
  };
  
  // Source data (VPIC) - placeholder for future enrichment
  vpic: {
    vpic_model_id: string | null;
    vehicle_types: string[];
    models_by_year: Record<string, unknown>;
  };
  
  // Source data (CarQuery) - placeholder for future enrichment
  carquery: {
    trim_id: string | null;
    trim_specs: Record<string, unknown>;
  };
  
  // Metadata
  sources: string[];                   // ["epa"] or ["epa", "vpic", "carquery"]
  createdAt: FirebaseFirestore.Timestamp;
  updatedAt: FirebaseFirestore.Timestamp;
}

/**
 * Metadata document structure
 * Collection: metadata/makes/{make}/stats
 */
export interface MakeMetadata {
  make: string;                        // "Toyota", "Lexus"
  years: number[];                     // [2024, 2025]
  counts_by_year: Record<string, number>; // { "2024": 45, "2025": 8 }
  lastUpdated: FirebaseFirestore.Timestamp;
  sources: string[];                   // ["epa"]
}

/**
 * User Profile document structure
 * Collection: userProfiles
 * Document ID: {auth0UserId}
 */
export interface UserProfile {
  userId: string;                      // Auth0 user ID (sub claim)
  email: string;
  name: string | null;
  favorites: string[];                 // Array of vehicle IDs
  comparedVehicles: string[];          // Recently compared vehicle IDs
  searchHistory: SearchHistoryEntry[];
  preferences: UserPreferences;
  createdAt: FirebaseFirestore.Timestamp;
  updatedAt: FirebaseFirestore.Timestamp;
}

export interface SearchHistoryEntry {
  timestamp: FirebaseFirestore.Timestamp;
  filters: {
    bodyStyle?: BodyStyle;
    fuelType?: Powertrain;
    maxPrice?: number;
    minSeating?: number;
  };
  resultsCount: number;
}

export interface UserPreferences {
  budgetType: 'monthly' | 'cash';
  budgetAmount: number | null;
  priorityMpg: boolean;
  prioritySafety: boolean;
  preferredDrivetrain?: Drivetrain;
  preferredBodyStyles: BodyStyle[];
}

/**
 * Dealer Lead document structure
 * Collection: dealerLeads
 * Document ID: auto-generated
 */
export interface DealerLead {
  userId: string;                      // Auth0 user ID
  vehicleIds: string[];                // IDs of vehicles user is interested in
  contactInfo: {
    name: string;
    email: string;
    phone: string;
  };
  zipCode: string;
  preferredContact: 'email' | 'phone' | 'text';
  message: string | null;
  consent: boolean;                    // Agreed to terms
  status: 'pending' | 'contacted' | 'completed';
  createdAt: FirebaseFirestore.Timestamp;
}

/**
 * Anonymous Session document (for unauthenticated users)
 * Collection: anonymousSessions
 * Document ID: {sessionId} (UUID)
 * TTL: 30 days (auto-deleted via Firestore TTL policy)
 */
export interface AnonymousSession {
  sessionId: string;
  favorites: string[];
  comparedVehicles: string[];
  lastActivity: FirebaseFirestore.Timestamp;
  expiresAt: FirebaseFirestore.Timestamp;
}
